name: nlp-course-fri
channels:
  - anaconda
  - huggingface
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - aiohttp=3.7.4=py36h27cfd23_1
  - argon2-cffi=20.1.0=py36h27cfd23_1
  - async-timeout=3.0.1=py36h06a4308_0
  - async_generator=1.10=py36h28b3542_0
  - attrs=20.3.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.9.3=pyha847dfd_0
  - blas=1.0=mkl
  - bleach=3.3.0=pyhd3eb1b0_0
  - boto3=1.17.46=pyhd3eb1b0_0
  - botocore=1.20.50=pyhd3eb1b0_1
  - brotlipy=0.7.0=py36h27cfd23_1003
  - bs4=4.9.3=hd3eb1b0_0
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2021.4.13=h06a4308_1
  - cachetools=4.2.1=pyhd3eb1b0_0
  - cairo=1.14.12=h8948797_3
  - certifi=2020.12.5=py36h06a4308_0
  - cffi=1.14.0=py36h2e261b9_0
  - chardet=3.0.4=py36h06a4308_1003
  - click=7.1.2=pyhd3eb1b0_0
  - cryptography=3.4.7=py36hd23ed53_0
  - cudatoolkit=11.0.221=h6bb024c_0
  - cycler=0.10.0=py36_0
  - dataclasses=0.8=pyh4f3eec9_6
  - dbus=1.13.18=hb2f20db_0
  - decorator=5.0.6=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.3=py36_0
  - expat=2.3.0=h2531618_2
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.0.12=pyhd3eb1b0_1
  - fontconfig=2.13.1=h6c09931_0
  - freetype=2.10.4=h5ab3b9f_0
  - fribidi=1.0.10=h7b6447c_0
  - gensim=3.8.3=py36h2531618_2
  - glib=2.63.1=h5a9c865_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - google-api-core=1.25.1=pyhd3eb1b0_0
  - google-auth=1.28.1=pyhd3eb1b0_0
  - google-cloud-core=1.6.0=pyhd3eb1b0_0
  - google-cloud-storage=1.37.1=pyhd3eb1b0_0
  - google-crc32c=1.1.2=py36h27cfd23_0
  - google-resumable-media=1.2.0=pyhd3eb1b0_1
  - googleapis-common-protos=1.53.0=py36h06a4308_0
  - graphite2=1.3.14=h23475e2_0
  - graphviz=2.40.1=h21bd128_2
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.10.0=py36hd6299e0_1
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.6=hb1b8bf9_0
  - icu=58.2=he6710b0_3
  - idna=2.10=pyhd3eb1b0_0
  - idna_ssl=1.1.0=py36h06a4308_0
  - importlib-metadata=3.10.0=py36h06a4308_0
  - importlib_metadata=3.10.0=hd3eb1b0_0
  - intel-openmp=2020.2=254
  - ipykernel=5.3.4=py36h5ca1d4c_0
  - ipython=7.16.1=py36h5ca1d4c_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.3=pyhd3deb0d_0
  - jedi=0.17.0=py36_0
  - jinja2=2.11.3=pyhd3eb1b0_0
  - jmespath=0.10.0=py_0
  - joblib=1.0.1=pyhd3eb1b0_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=3.2.0=py_2
  - jupyter_client=6.1.12=pyhd3eb1b0_0
  - jupyter_core=4.7.1=py36h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_widgets=1.0.0=pyhd8ed1ab_1
  - kiwisolver=1.3.1=py36h2531618_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libcrc32c=1.1.1=he6710b0_2
  - libffi=3.2.1=hf484d3e_1007
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.15=h63c8f33_5
  - libidn2=2.3.0=h27cfd23_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.14.0=h8c45485_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.1.0=h2733197_1
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.0.3=h1bed415_2
  - libuv=1.40.0=h7b6447c_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=hb55368b_3
  - lz4-c=1.9.3=h2531618_0
  - markupsafe=1.1.1=py36h7b6447c_0
  - matplotlib=3.3.4=py36h06a4308_0
  - matplotlib-base=3.3.4=py36h62a2d02_0
  - mistune=0.8.4=py36h7b6447c_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py36he8ac12f_0
  - mkl_fft=1.3.0=py36h54f3939_0
  - mkl_random=1.1.1=py36h0573a6f_0
  - mpld3=0.5.2=py36h06a4308_0
  - multidict=5.1.0=py36h27cfd23_2
  - nb_conda=2.2.1=py36_0
  - nb_conda_kernels=2.3.1=py36h06a4308_0
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nbconvert=6.0.7=py36_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - ncurses=6.2=he6710b0_1
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - nettle=3.7.2=hbbd107a_1
  - ninja=1.10.2=hff7bd54_1
  - nltk=3.6.1=pyhd3eb1b0_0
  - notebook=6.3.0=py36h06a4308_0
  - numpy=1.19.2=py36h54aff64_0
  - numpy-base=1.19.2=py36hfa32c7d_0
  - olefile=0.46=py36_0
  - openh264=2.1.0=hd408876_0
  - openssl=1.1.1k=h27cfd23_0
  - packaging=20.9=pyhd3eb1b0_0
  - pandas=1.1.5=py36ha9443f7_0
  - pandoc=2.12=h06a4308_0
  - pandocfilters=1.4.3=py36h06a4308_1
  - pango=1.42.4=h049681c_0
  - parso=0.8.2=pyhd3eb1b0_0
  - pcre=8.44=he6710b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.2.0=py36he98fc37_0
  - pip=21.0.1=py36h06a4308_0
  - pixman=0.40.0=h7b6447c_0
  - prometheus_client=0.10.1=pyhd3eb1b0_0
  - prompt-toolkit=3.0.17=pyh06a4308_0
  - protobuf=3.14.0=py36h2531618_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.20=py_2
  - pydot=1.4.1=py36h06a4308_0
  - pygments=2.8.1=pyhd3eb1b0_0
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py36h05f1152_2
  - pyrsistent=0.17.3=py36h7b6447c_0
  - pysocks=1.7.1=py36h06a4308_0
  - python=3.6.10=hcf32534_1
  - python-crfsuite=0.9.7=py36h2531618_1
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - python_abi=3.6=1_cp36m
  - pytorch=1.7.1=py3.6_cuda11.0.221_cudnn8.0.5_0
  - pytz=2021.1=pyhd3eb1b0_0
  - pyzmq=20.0.0=py36h2531618_1
  - qt=5.9.7=h5867ecd_1
  - readline=8.1=h27cfd23_0
  - regex=2021.4.4=py36h27cfd23_0
  - requests=2.25.1=pyhd3eb1b0_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - s3transfer=0.3.6=pyhd3eb1b0_0
  - sacremoses=master=py_0
  - scipy=1.5.2=py36h0b6359f_0
  - seaborn=0.11.1=pyhd3eb1b0_0
  - send2trash=1.5.0=pyhd3eb1b0_1
  - setuptools=52.0.0=py36h06a4308_0
  - sip=4.19.8=py36hf484d3e_0
  - six=1.15.0=py36h06a4308_0
  - smart_open=5.0.0=pyhd3eb1b0_0
  - soupsieve=2.2.1=pyhd3eb1b0_0
  - sqlite=3.35.4=hdfb4753_0
  - terminado=0.9.4=py36h06a4308_0
  - testpath=0.4.4=pyhd3eb1b0_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hbc83047_0
  - tokenizers=0.10.2=py36_0
  - torchaudio=0.7.2=py36
  - torchvision=0.8.2=py36_cu110
  - tornado=6.1=py36h27cfd23_0
  - tqdm=4.59.0=pyhd3eb1b0_1
  - traitlets=4.3.3=py36_0
  - transformers=4.4.2=py_0
  - typing-extensions=3.7.4.3=hd3eb1b0_0
  - typing_extensions=3.7.4.3=pyh06a4308_0
  - urllib3=1.26.4=pyhd3eb1b0_0
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py36_1
  - wheel=0.36.2=pyhd3eb1b0_0
  - widgetsnbextension=3.5.1=py36h5fab9bb_4
  - xz=5.2.5=h7b6447c_0
  - yarl=1.5.1=py36h7b6447c_0
  - zeromq=4.3.4=h2531618_0
  - zipp=3.4.1=pyhd3eb1b0_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - absl-py==0.12.0
    - astunparse==1.6.3
    - flatbuffers==1.12
    - gast==0.3.3
    - google-auth-oauthlib==0.4.4
    - google-pasta==0.2.0
    - grpcio==1.32.0
    - keras==2.4.3
    - keras-preprocessing==1.1.2
    - markdown==3.3.4
    - oauthlib==3.1.0
    - opt-einsum==3.3.0
    - pyyaml==5.4.1
    - requests-oauthlib==1.3.0
    - scikit-learn==0.24.1
    - seqeval==1.2.2
    - tensorboard==2.5.0
    - tensorboard-data-server==0.6.0
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==2.4.1
    - tensorflow-estimator==2.4.0
    - termcolor==1.1.0
    - werkzeug==1.0.1
    - wrapt==1.12.1
    - classla==1.1.0
prefix: /home/slavkoz/anaconda3/envs/nlp-course-fri-2
